// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNameBlockRPC = "blocks_rpc"

// Block mapped from table <blocks>
type BlockRPC struct {
	Number     int64  `gorm:"column:number;primaryKey" json:"number"`
	Hash       string `gorm:"column:hash;not null" json:"hash"`
	ParentHash string `gorm:"column:parent_hash;not null" json:"parent_hash"`
}

// TableName Block's table name
func (*BlockRPC) TableName() string {
	return TableNameBlockRPC
}
